# Generated by Django 4.2.2 on 2023-06-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adventures", "0002_adventure_latitude_adventure_longitude"),
    ]

    operations = [
        migrations.AddField(
            model_name="adventure",
            name="adrenalin",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adventure",
            name="kid",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adventure",
            name="promoted",
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
