# Generated by Django 4.2.2 on 2023-06-19 09:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("adventures", "0003_adventure_adrenalin_adventure_kid_adventure_promoted"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adventure",
            old_name="kid",
            new_name="kids",
        ),
    ]
